### ISSUE TITLE
spotify

### ISSUE THREAD

**Issue by tonjesteff** [ryanb93/Applefy#23]
i can't get logged in because it says that i dont have spotify premium. But i do. 
What can i do to fix this?

**Comment by ryanb93** [comment]
Hi,

This project is no longer supported or in a working state since the technique no longer works.

Thanks

On 10 Oct 2017, at 09:39, tonjesteff <notifications@github.com<mailto:notifications@github.com>> wrote:


i can't get logged in because it says that i dont have spotify premium. But i do.
What can i do to fix this?
