### ISSUE TITLE
iTunes Match support?

### ISSUE THREAD

**Issue by MartinAyla** [ryanb93/Applefy#3]
Hi Ryan

I just donated 5 Pounds, for coffee :)

I hope you can find a workaround for us that have iTunes Match.

It's almost working - I can right-click on individual files and 'add to iCloud Music Library' and most of them will be added. It's just a very slow to for every song.

Thanks
Martin

**Comment by ryanb93** [comment]
Unfortunately this only works because Apple assumes you have the full song and so adds the song to your online library without actually uploading the song. If you have iTunes Match, it seems that the default behaviour is to upload the MP3 file itself, this results in the 5 second clip being uploaded. I think the only way to stop this is to cancel your Match subscription with immediate effect. Thank you very much for the donation :)

**Comment by MartinAyla** [comment]
Thanks, I have cancelled my iTunes Match now.
